name: CI
on: pull_request 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: server
      run: yarn
    - name: Run tests
      working-directory: server
      run: yarn test